services:
  php:
    build:
      context: ./php
    image: ${PREFIX}-app
    container_name: ${PREFIX}-app
    volumes:
      - ../:/var/www:delegated
      - ./logs/supervisor:/var/log/supervisor
      - ./logs/cron:/var/log/cron
    expose:
      - "9000"
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      github_repo_tracker:
        aliases:
          - github-repo-tracker-app

  nginx:
    build:
      context: ./nginx
      args:
        - PREFIX=${PREFIX}
        - PHP_UPSTREAM_CONTAINER=${PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${PHP_UPSTREAM_PORT}
    image: ${PREFIX}-nginx
    container_name: ${PREFIX}-nginx
    working_dir: /var/www
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ../:/var/www:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
    depends_on:
      - php
    networks:
      - github_repo_tracker

  postgres:
    image: ${PREFIX}-postgres
    container_name: ${PREFIX}-postgres
    build:
      context: ./postgres
      args:
        - VERSION=${POSTGRES_VERSION}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    depends_on:
      - php
    networks:
      - github_repo_tracker

volumes:
  db_data:

networks:
  github_repo_tracker:
    driver: bridge
